aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:minhachaveacessoweb}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:minhachaveacessosecreta}
  region: ${AWS_REGION:regiaopadrao}

san-zancanela-api:
  aws:
    accountId: ${AWS_ACCOUNT_ID:minhaconta}

spring:
  aplication:
    name: san-zancanela-api
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

